### PR TITLE
Feedback form changes

### PR DESCRIPTION
**Pull request by jsiems**
Layout changes for the feedback form. To be merged after feedback branch is merged.

Only look at the commits made my jsiems.

To see it, go to [my site](https://ama-jsiems.c9users.io), and click on the submit feedback button in the footer. It should be up until I switch my branch.

### CODE REVIEW

**Comment by jsiems** [comment]
Name of that last commit is supposed to be: Made form not as wide on desktop

**Comment by s1037989** [comment]
Clicked on the button and it popped up.  Great!  Typed a message and clicked submit and nothing happened.  I assume Andy's feedback feature is not yet wired in?

**Comment by s1037989** [comment]
:+1:

**Comment by jsiems** [comment]
Unfortunately, yes, it will not work on my branch because I don't have the password for Andy's email address.

We were thinking about creating a new dummy email called amafeedback@keystone-it.com or something and using that to send out the feedback, that way we can use a password that does not need to be private.

**Comment by s1037989** [comment]
You shouldn't need to know Andy's password to deliver a message.  Tell me more about why you think this is necessary.

**Comment by jsiems** [comment]
Right now the program is using Andy's email to log in to Sendgrid to send out the feedback emails.

Talk to @andygoodday if you have any more questions about how that works, I really don't know any more than that.

**Comment by s1037989** [comment]
Ah gotcha!  Yes, excellent.  It's not a username / password, so you could just ask him for the API Key that he uses and put that in your ama.conf.

**Pull request merged**
