### PR TITLE
XSS fix | OSX/iOS question fix | reorder answered questions

### PR DESCRIPTION
**Pull request by meyerben**
#58

xss

### CODE REVIEW

**Comment by meyerben** [comment]
#59 Rather than creating a way to order questions, I've made a quick edit that orders answered questions by newest to oldest rather than vote count. 

I'm assuming users would rarely be interested in the highest rated question of all time. It makes more sense to browse through recently answered questions.

If there is more interest, a sorting option could be added.

**Comment by s1037989** [comment]
Great!

How does this relate to XSS?

**Comment by meyerben** [comment]
It doesn't. I have multiple commits for different issues, but can only make one pull request for my branch.

**Comment by s1037989** [comment]
Most of these changes were included in #61.  Create a new PR for anything missed.

**Pull request closed without merging**
