### PR TITLE
confirmation box added before someone deleting question and comment

### PR DESCRIPTION
**Pull request by andygoodday**
Each time before someone trying to delete question and comment, there will be a confirmation box displayed to ask "are you sure you want to delete?" There will be two options. One button is "OK", the other button is "Cancel". That post message will be deleted if you click ok. The delete request will be canceled if you click cancel.

### CODE REVIEW

**Comment by meyerben** [comment]
I noticed that if the user blocks popups, they have no way of deleting a question or comment. (unable to set confirmDelete to true)

I think it would also be beneficial to move confirmDelete to /public/ js/scripts.js

**Comment by jsiems** [comment]
Looks good. Eventually a few styling things will need to change to stay with the document, but for now lets go with what works

**Comment by s1037989** [comment]
Something doesn't look right.  L179 and L266 refer to deletePost, but L179 has `ID` as the parameter and L266 has `'ID'` as the parameter.

**Comment by jsiems** [comment]
I added the quotes a while ago to try and fix a strange bug. Turns out that adding be quotes did not fix the problem, but I did eventually fix it and forgot to remove them.

JavaScript tries to automatically translates between data types  so having the ID as a string does not change anything, but eventually we should get rid of the quotes for the sake of consistency.

**Comment by s1037989** [comment]
@meyerben Good catch, Ben and I did talk about this and he's going to proceed with the js dialog box and then move on to an HTML dialog box.
@jsiems So it sounds like @andygoodday implemented your function API correctly.

**Pull request merged**
