### PR TITLE
redirect to https

### PR DESCRIPTION
**Pull request by andygoodday**
@meyerben For Ben test outside of cloud 9 environment.

### CODE REVIEW

**Comment by meyerben** [comment]
:+1:

**Comment by s1037989** [comment]
Did you try to use the existing plugin, M::P::SecureOnly?  It would be better to use existing plugins than to reinvent any wheels.

**Comment by s1037989** [comment]
:+1:

Terrific!  @meyerben working on testing this?

**Comment by jsiems** [comment]
:+1:

**Pull request merged**
